services:
  # Backend servisleri
  web:
    build: ./backend
    command: >
      bash -c "python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 120"
    volumes:
      - ./backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-jmxlyorkuj7v-qal9_@_v3o=_u*y3!0(+kfk7xa^y8uv^e^a
      - DATABASE_URL=postgres://ecommerce_user:ecommerce_pass@postgres:5432/ecommerce
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - FRONTEND_URL=https://kasarcim.com

  # Frontend servisi
  frontend:
    build: ./frontend
    depends_on:
      - web
    expose:
      - 3000

  # Nginx servisi
  nginx:
    image: nginx:1.23-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "90:80"
    depends_on:
      - web
      - frontend

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: kasarcim
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ardahan91185.
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: ./backend
    command: celery -A ecommerce worker -l INFO
    volumes:
      - ./backend:/app
    depends_on:
      - web
      - redis
      - postgres
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-jmxlyorkuj7v-qal9_@_v3o=_u*y3!0(+kfk7xa^y8uv^e^a
      - DATABASE_URL=postgres://ecommerce_user:ecommerce_pass@postgres:5432/ecommerce
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-beat:
    build: ./backend
    command: celery -A ecommerce beat -l INFO
    volumes:
      - ./backend:/app
    depends_on:
      - web
      - redis
      - postgres
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-jmxlyorkuj7v-qal9_@_v3o=_u*y3!0(+kfk7xa^y8uv^e^a
      - DATABASE_URL=postgres://ecommerce_user:ecommerce_pass@postgres:5432/ecommerce
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  postgres_data:
  static_volume:
  media_volume:
