# Generated by Django 5.1.3 on 2025-05-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_shipping_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cod_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("online", "Online Ödeme"),
                    ("cash_on_delivery", "Kapıda Ödeme"),
                ],
                default="online",
                max_length=20,
            ),
        ),
    ]
