# Generated by Django 4.2.21 on 2025-05-17 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_cod_fee_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preparing', 'Hazırlanıyor'), ('shipped', 'Kargoya Verildi'), ('in_transit', 'Yolda'), ('out_for_delivery', 'Dağıtıma Çıktı'), ('delivered', 'Teslim Edildi'), ('failed', 'Teslim Başarısız'), ('returned', 'İade Edildi')], default='preparing', max_length=20)),
                ('shipping_company', models.CharField(choices=[('aras', 'Aras Kargo'), ('yurtici', 'Yurtiçi Kargo'), ('mng', 'MNG Kargo'), ('ptt', 'PTT Kargo'), ('ups', 'UPS'), ('surat', 'Sürat Kargo'), ('other', 'Diğer')], default='aras', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_url', models.URLField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Kargo',
                'verbose_name_plural': 'Kargolar',
                'ordering': ['-created_at'],
            },
        ),
    ]
