# Generated by Django 5.1.3 on 2025-05-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_productimage_productrating_productreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="dislike",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productreview",
            name="like",
            field=models.IntegerField(default=0),
        ),
    ]
