# Generated by Django 4.2.21 on 2025-05-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productreview_dislike_productreview_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
