# Generated by Django 4.2.21 on 2025-05-23 00:03

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='URL Slug')),
                ('excerpt', models.TextField(help_text='Blog yazısının kısa özeti', verbose_name='Özet')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='İçerik')),
                ('featured_image', models.ImageField(help_text='Ana görsel, 1200x630px önerilen boyut', upload_to='blog/images/%Y/%m/', verbose_name='Kapak Görseli')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayınlandı')], default='draft', max_length=10, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Yayınlanma Tarihi')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('meta_description', models.CharField(blank=True, help_text='SEO için 160 karakterden az olmalı', max_length=160, verbose_name='Meta Açıklama')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sayısı')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Blog Kategorisi',
                'verbose_name_plural': 'Blog Kategorileri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Etiket Adı')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='URL Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Blog Etiketi',
                'verbose_name_plural': 'Blog Etiketleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=220, verbose_name='URL Slug')),
                ('level', models.IntegerField(default=2, help_text='2: H2, 3: H3', verbose_name='Seviye')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blog.blog', verbose_name='Blog Yazısı')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.blogsection', verbose_name='Üst Başlık')),
            ],
            options={
                'verbose_name': 'Blog Bölümü',
                'verbose_name_plural': 'Blog Bölümleri',
                'ordering': ['blog', 'order'],
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(related_name='blogs', to='blog.blogcategory', verbose_name='Kategoriler'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='blog.blogtag', verbose_name='Etiketler'),
        ),
    ]
