# Generated by Django 4.2.21 on 2025-05-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsection',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Bölüm İçeriği'),
        ),
    ]
