# Generated by Django 4.2.21 on 2025-05-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogsection_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.URLField(help_text="CDN üzerindeki görsel URL'si (1200x630px önerilen boyut)", max_length=500, verbose_name='Kapak Görseli URL'),
        ),
    ]
