# Generated by Django 4.2.21 on 2025-05-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Duyuru Metni')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bağlantı URL')),
                ('link_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bağlantı Metni')),
                ('background_color', models.CharField(default='bg-orange-500', max_length=20, verbose_name='Arka Plan Rengi')),
                ('text_color', models.CharField(default='text-white', max_length=20, verbose_name='Yazı Rengi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
